trigger:
  - master
pr:
  - master

resources:
  repositories:
    - repository: templates
      type: github
      name: ius-gov/pipeline-templates
      endpoint: ius-dev

variables:
  project: "ius.tax.umbrella"
jobs:
  - template: helm/standalone-helm-chart-pipeline.yaml@templates
    parameters:
      project: 'common-template'
      helmChartLocation: '.'
      helmChartName: 'tax-umbrella'
      stateCode: 0
