{{- define "common.ingress" -}}
{{- $common := dict "Values" .Values.common -}} 
{{- $noCommon := omit .Values "common" -}} 
{{- $overrides := dict "Values" $noCommon -}} 
{{- $noValues := omit . "Values" -}} 
{{- $ingressOverride := dict .Values "ingressoverride" -}} 
{{- with merge $noValues $overrides $common -}}
apiVersion: extensions/v1beta1
kind: Ingress
{{ template "common.metadata" . }}
{{- with .Values.global.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- if $ingressOverride }}
{{- if (hasKey $ingressOverride "common.fullname") }}
{{ merge ".Values.ingressoverride" "common.fullname" }}
{{- with (merge ".Values.ingressoverride" "common.fullname") }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
spec:
{{- if .Values.ingress.enabletls }}
  tls:
  - hosts:
    - {{ include "common.url" . }}
    secretName: {{ .Values.global.ingress.tlssecret}}
{{- end }}
  rules:
  - host: {{ include "common.url" . }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ include "common.fullname" . }}
            servicePort: 80
{{- end }}
{{- end }}