# Default values for services
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  tag: 0.0.0-INTERNAL
  pullPolicy: Always

clientStateName : Consortium
Environment : Development
LoggingKey: ""
AppSettingsLocation: /app/appsettings
AppSettingsConfigMap: appsettings-cm
ImagePullSecret: iusdev



nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

global:
  servicePrefix: ""
  ingress:
    host: localhost
    annotations:
      kubernetes.io/ingress.class: addon-http-application-routing
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
      nginx.ingress.kubernetes.io/proxy-buffering: "on"
  