# Default values for services
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


image:
  tag: 0.0.0-INTERNAL
  pullPolicy: IfNotPresent

ImagePullSecret: iusdev
LoggingKey: ""

AppSettingsLocation: ""

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80


resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

ingress:
  enabletls: true

global:
  minReadySeconds: 5
  ClientStateName : Consortium
  Environment : Development
  replicaCount: 1
  ingress:
    tlssecret: tls-secret
    host: "***global.ingress.host needs a value***"
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
      nginx.ingress.kubernetes.io/proxy-buffering: "on"
      kubernetes.io/ingress.class: nginx
# TODO replace this with a call to the new endpoint that returns 400 on unhealthy
  ReadinessProbe:
    exec:
      command:
      - /bin/bash
      - -c
      - checkHealth () { echo "******begin health check******"; res=`curl -s http://localhost/health --insecure`; echo $res; if [[  `curl -s http://localhost/health --insecure  | awk '{gsub(",\"checks\":\\\[.*\\\]", "");print}' |  grep -zoP '"status_code":\s*\K[^\s,]*(?=\s*,)'` == 0* ]] ; then return 0 ; else return  1; fi } && checkHealth
  additional_env_vars: []