# Default values for services
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


image:
  tag: 0.0.0-INTERNAL
  pullPolicy: Always

LoggingKey: ""

AppSettingsLocation: /app/appsettings

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

ingress:
  enabletls: true

global:
  clientStateName : Consortium
  Environment : Development
  replicaCount: 1
  ImagePullSecret: iusdev
  ingress:
    tlssecret: tls-secret
    host: localhost
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
      nginx.ingress.kubernetes.io/proxy-buffering: "on"
      kubernetes.io/ingress.class: nginx

  