replicaCount: 1

image:
  repository: iusdev.azurecr.io/ius.employerwages.service
  tag: 0.2.9.2502


nameOverride: ""
fullnameOverride: ""


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

global:
  ClientStateName: "State"
  Environment: "Envrionment"
  ingress:
    host: k8-ius.com

additional_env_vars: 
  betterStateName: cmon-just-work
  Debug_level: "super duper uper vuper verbos"
  APPSETTINGS_LOCATION: "hmmmm what happens now"